services:
  qr-gen-app:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    restart: always
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true